/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 lsw.gltf -t
*/

import * as THREE from 'three'
import { useGLTF, Html  } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { BiSearchAlt } from 'react-icons/bi'
import { ISidebarContent } from '../interfaces/sidebarContent'
import { lswData } from '../data/lswData'

type GLTFResult = GLTF & {
  nodes: {
    Garden_Shrine_lambert7_0: THREE.Mesh
    Fountain_Fountain_0: THREE.Mesh
    Cylinder_0: THREE.Mesh
    Icosphere_0: THREE.Mesh
    Icosphere001_0: THREE.Mesh
    Icosphere002_0: THREE.Mesh
    Icosphere003_0: THREE.Mesh
    Icosphere004_0: THREE.Mesh
    Icosphere005_0: THREE.Mesh
    Cylinder_0010: THREE.Mesh
    Icosphere_0010: THREE.Mesh
    Icosphere001_0010: THREE.Mesh
    Icosphere002_0010: THREE.Mesh
    Icosphere003_0010: THREE.Mesh
    Icosphere004_0010: THREE.Mesh
    Icosphere005_0010: THREE.Mesh
    ['Icosphere001_mattree-elm_0']: THREE.Mesh
    Object_2009: THREE.Mesh
    Object_0008: THREE.Mesh
    Object_0008_1: THREE.Mesh
    Object_0003: THREE.Mesh
    Object_0003_1: THREE.Mesh
    Object_0013: THREE.Mesh
    Object_0013_1: THREE.Mesh
    Object_0002: THREE.Mesh
    Object_0002_1: THREE.Mesh
    Object_0004: THREE.Mesh
    Object_0004_1: THREE.Mesh
    Cylinder_0001: THREE.Mesh
    Icosphere005_0001: THREE.Mesh
    Icosphere004_0001: THREE.Mesh
    Icosphere003_0001: THREE.Mesh
    Icosphere002_0001: THREE.Mesh
    Icosphere001_0001: THREE.Mesh
    Icosphere_0001: THREE.Mesh
    Cylinder_0002: THREE.Mesh
    Icosphere_0002: THREE.Mesh
    Icosphere001_0002: THREE.Mesh
    Icosphere002_0002: THREE.Mesh
    Icosphere003_0002: THREE.Mesh
    Icosphere004_0002: THREE.Mesh
    Icosphere005_0002: THREE.Mesh
    Cylinder_0003: THREE.Mesh
    Icosphere005_0003: THREE.Mesh
    Icosphere004_0003: THREE.Mesh
    Icosphere003_0003: THREE.Mesh
    Icosphere002_0003: THREE.Mesh
    Icosphere001_0003: THREE.Mesh
    Icosphere_0003: THREE.Mesh
    Cylinder_0004: THREE.Mesh
    Icosphere_0004: THREE.Mesh
    Icosphere001_0004: THREE.Mesh
    Icosphere002_0004: THREE.Mesh
    Icosphere003_0004: THREE.Mesh
    Icosphere004_0004: THREE.Mesh
    Icosphere005_0004: THREE.Mesh
    Cylinder_0005: THREE.Mesh
    Icosphere005_0005: THREE.Mesh
    Icosphere004_0005: THREE.Mesh
    Icosphere003_0005: THREE.Mesh
    Icosphere002_0005: THREE.Mesh
    Icosphere001_0005: THREE.Mesh
    Icosphere_0005: THREE.Mesh
    Cylinder_0006: THREE.Mesh
    Icosphere005_0006: THREE.Mesh
    Icosphere004_0006: THREE.Mesh
    Icosphere003_0006: THREE.Mesh
    Icosphere002_0006: THREE.Mesh
    Icosphere001_0006: THREE.Mesh
    Icosphere_0006: THREE.Mesh
    Cylinder_0007: THREE.Mesh
    Icosphere_0007: THREE.Mesh
    Icosphere001_0007: THREE.Mesh
    Icosphere002_0007: THREE.Mesh
    Icosphere003_0007: THREE.Mesh
    Icosphere004_0007: THREE.Mesh
    Icosphere005_0007: THREE.Mesh
    Cylinder_0008: THREE.Mesh
    Icosphere005_0008: THREE.Mesh
    Icosphere004_0008: THREE.Mesh
    Icosphere003_0008: THREE.Mesh
    Icosphere002_0008: THREE.Mesh
    Icosphere001_0008: THREE.Mesh
    Icosphere_0008: THREE.Mesh
    Cylinder_0009: THREE.Mesh
    Icosphere_0009: THREE.Mesh
    Icosphere001_0009: THREE.Mesh
    Icosphere002_0009: THREE.Mesh
    Icosphere003_0009: THREE.Mesh
    Icosphere004_0009: THREE.Mesh
    Icosphere005_0009: THREE.Mesh
    Cylinder_0011: THREE.Mesh
    Icosphere005_0011: THREE.Mesh
    Icosphere004_0011: THREE.Mesh
    Icosphere003_0011: THREE.Mesh
    Icosphere002_0011: THREE.Mesh
    Icosphere001_0011: THREE.Mesh
    Icosphere_0011: THREE.Mesh
    Cylinder_0012: THREE.Mesh
    Icosphere_0012: THREE.Mesh
    Icosphere001_0012: THREE.Mesh
    Icosphere002_0012: THREE.Mesh
    Icosphere003_0012: THREE.Mesh
    Icosphere004_0012: THREE.Mesh
    Icosphere005_0012: THREE.Mesh
    Cylinder_0013: THREE.Mesh
    Icosphere005_0013: THREE.Mesh
    Icosphere004_0013: THREE.Mesh
    Icosphere003_0013: THREE.Mesh
    Icosphere002_0013: THREE.Mesh
    Icosphere001_0013: THREE.Mesh
    Icosphere_0013: THREE.Mesh
    Cylinder_0014: THREE.Mesh
    Icosphere_0014: THREE.Mesh
    Icosphere001_0014: THREE.Mesh
    Icosphere002_0014: THREE.Mesh
    Icosphere003_0014: THREE.Mesh
    Icosphere004_0014: THREE.Mesh
    Icosphere005_0014: THREE.Mesh
    Cylinder_0015: THREE.Mesh
    Icosphere005_0015: THREE.Mesh
    Icosphere004_0015: THREE.Mesh
    Icosphere003_0015: THREE.Mesh
    Icosphere002_0015: THREE.Mesh
    Icosphere001_0015: THREE.Mesh
    Icosphere_0015: THREE.Mesh
    Cylinder_0016: THREE.Mesh
    Icosphere_0016: THREE.Mesh
    Icosphere001_0016: THREE.Mesh
    Icosphere002_0016: THREE.Mesh
    Icosphere003_0016: THREE.Mesh
    Icosphere004_0016: THREE.Mesh
    Icosphere005_0016: THREE.Mesh
    Cylinder_0017: THREE.Mesh
    Icosphere005_0017: THREE.Mesh
    Icosphere004_0017: THREE.Mesh
    Icosphere003_0017: THREE.Mesh
    Icosphere002_0017: THREE.Mesh
    Icosphere001_0017: THREE.Mesh
    Icosphere_0017: THREE.Mesh
    Cylinder_0018: THREE.Mesh
    Icosphere_0018: THREE.Mesh
    Icosphere001_0018: THREE.Mesh
    Icosphere002_0018: THREE.Mesh
    Icosphere003_0018: THREE.Mesh
    Icosphere004_0018: THREE.Mesh
    Icosphere005_0018: THREE.Mesh
    Cylinder_0019: THREE.Mesh
    Icosphere005_0019: THREE.Mesh
    Icosphere004_0019: THREE.Mesh
    Icosphere003_0019: THREE.Mesh
    Icosphere002_0019: THREE.Mesh
    Icosphere001_0019: THREE.Mesh
    Icosphere_0019: THREE.Mesh
    Cylinder_0020: THREE.Mesh
    Icosphere_0020: THREE.Mesh
    Icosphere001_0020: THREE.Mesh
    Icosphere002_0020: THREE.Mesh
    Icosphere003_0020: THREE.Mesh
    Icosphere004_0020: THREE.Mesh
    Icosphere005_0020: THREE.Mesh
    Cylinder_0021: THREE.Mesh
    Icosphere005_0021: THREE.Mesh
    Icosphere004_0021: THREE.Mesh
    Icosphere003_0021: THREE.Mesh
    Icosphere002_0021: THREE.Mesh
    Icosphere001_0021: THREE.Mesh
    Icosphere_0021: THREE.Mesh
    Cylinder_0022: THREE.Mesh
    Icosphere_0022: THREE.Mesh
    Icosphere001_0022: THREE.Mesh
    Icosphere002_0022: THREE.Mesh
    Icosphere003_0022: THREE.Mesh
    Icosphere004_0022: THREE.Mesh
    Icosphere005_0022: THREE.Mesh
    ['Icosphere001_mattree-elm_0001']: THREE.Mesh
    ['Icosphere001_mattree-elm_0002']: THREE.Mesh
    ['Icosphere001_mattree-elm_0003']: THREE.Mesh
    ['Icosphere001_mattree-elm_0004']: THREE.Mesh
    ['Icosphere001_mattree-elm_0005']: THREE.Mesh
    ['Icosphere001_mattree-elm_0006']: THREE.Mesh
    ['Icosphere001_mattree-elm_0007']: THREE.Mesh
    ['Icosphere001_mattree-elm_0008']: THREE.Mesh
    ['Icosphere001_mattree-elm_0009']: THREE.Mesh
    ['Icosphere001_mattree-elm_0010']: THREE.Mesh
    ['Icosphere001_mattree-elm_0011']: THREE.Mesh
    ['Icosphere001_mattree-elm_0012']: THREE.Mesh
    ['Icosphere001_mattree-elm_0013']: THREE.Mesh
    Cube003_1: THREE.Mesh
    Cube003_2: THREE.Mesh
    Cube019_1: THREE.Mesh
    Cube019_2: THREE.Mesh
    Cube019_3: THREE.Mesh
    Cube019_4: THREE.Mesh
    Cube019_5: THREE.Mesh
    Cube019_6: THREE.Mesh
    Cube022_1: THREE.Mesh
    Cube022_2: THREE.Mesh
    Cube005: THREE.Mesh
    Cube005_1: THREE.Mesh
    Cube007_1: THREE.Mesh
    Cube007_2: THREE.Mesh
    Cube009_1: THREE.Mesh
    Cube009_2: THREE.Mesh
    Cube011_1: THREE.Mesh
    Cube011_2: THREE.Mesh
    Cube011_3: THREE.Mesh
    Cube012_1: THREE.Mesh
    Cube012_2: THREE.Mesh
    Cube013_1: THREE.Mesh
    Cube013_2: THREE.Mesh
    Cube013_3: THREE.Mesh
    Cube013_4: THREE.Mesh
    Cube013_5: THREE.Mesh
    Cube006_1: THREE.Mesh
    Cube006_2: THREE.Mesh
    Cube019: THREE.Mesh
    Cube022: THREE.Mesh
    Cylinder001: THREE.Mesh
    Cube024: THREE.Mesh
    Cube023: THREE.Mesh
    ทรงกระบอก001: THREE.Mesh
    Cube025: THREE.Mesh
    ทรงกระบอก002: THREE.Mesh
    ทรงกระบอก003: THREE.Mesh
    Cube091: THREE.Mesh
    Cube092: THREE.Mesh
    Cube093: THREE.Mesh
    Cube094: THREE.Mesh
    Cube095: THREE.Mesh
    Cube096: THREE.Mesh
    Cube097: THREE.Mesh
    Cube098: THREE.Mesh
    Cube100: THREE.Mesh
    Cube100_1: THREE.Mesh
    Cylinder016: THREE.Mesh
    Cylinder024: THREE.Mesh
    ลูกบาศก์007: THREE.Mesh
    ลูกบาศก์005: THREE.Mesh
    ลูกบาศก์004: THREE.Mesh
    ลูกบาศก์003: THREE.Mesh
    ลูกบาศก์001: THREE.Mesh
    Cylinder042: THREE.Mesh
    Cylinder046: THREE.Mesh
    Cube103: THREE.Mesh
    Cube049: THREE.Mesh
    Cube049_1: THREE.Mesh
    Cube064: THREE.Mesh
    Cube062: THREE.Mesh
    Cube063: THREE.Mesh
    ลูกบาศก์002: THREE.Mesh
    ลูกบาศก์006: THREE.Mesh
    ลูกบาศก์008: THREE.Mesh
    ลูกบาศก์009: THREE.Mesh
    ลูกบาศก์016: THREE.Mesh
    ลูกบาศก์016_1: THREE.Mesh
    ลูกบาศก์016_2: THREE.Mesh
    ลูกบาศก์016_3: THREE.Mesh
    Cube001: THREE.Mesh
    Cube051: THREE.Mesh
    Cube051_1: THREE.Mesh
    Cube003: THREE.Mesh
    Cube069: THREE.Mesh
    Cube077: THREE.Mesh
    Cube072: THREE.Mesh
    Cube072_1: THREE.Mesh
    Cube072_2: THREE.Mesh
    Cube023_1: THREE.Mesh
    Cube023_2: THREE.Mesh
    Cube024_1: THREE.Mesh
    Cube024_2: THREE.Mesh
    Cube026_1: THREE.Mesh
    Cube026_2: THREE.Mesh
    Cube028_1: THREE.Mesh
    Cube028_2: THREE.Mesh
    Cube029_1: THREE.Mesh
    Cube029_2: THREE.Mesh
    Cube030_1: THREE.Mesh
    Cube030_2: THREE.Mesh
    Cube031_1: THREE.Mesh
    Cube031_2: THREE.Mesh
    Cube032_1: THREE.Mesh
    Cube032_2: THREE.Mesh
    Cube033_1: THREE.Mesh
    Cube033_2: THREE.Mesh
    Cube034_1: THREE.Mesh
    Cube034_2: THREE.Mesh
    Cube035_1: THREE.Mesh
    Cube035_2: THREE.Mesh
    Cube036_1: THREE.Mesh
    Cube036_2: THREE.Mesh
    Cube037_1: THREE.Mesh
    Cube037_2: THREE.Mesh
    Cube038_1: THREE.Mesh
    Cube038_2: THREE.Mesh
    Cube039_1: THREE.Mesh
    Cube039_2: THREE.Mesh
    Cube040_1: THREE.Mesh
    Cube040_2: THREE.Mesh
    Cube041_1: THREE.Mesh
    Cube041_2: THREE.Mesh
    Cube042: THREE.Mesh
    Cube042_1: THREE.Mesh
    Cube043: THREE.Mesh
    Cube043_1: THREE.Mesh
    Cube044: THREE.Mesh
    Cube044_1: THREE.Mesh
    Cube045: THREE.Mesh
    Cube045_1: THREE.Mesh
    Cube046: THREE.Mesh
    Cube046_1: THREE.Mesh
  }
  materials: {
    ['Material.103']: THREE.MeshStandardMaterial
    ['Material.137']: THREE.MeshStandardMaterial
    tree_wood: THREE.MeshStandardMaterial
    ['leaf_green.003']: THREE.MeshStandardMaterial
    ['leaf_green.004']: THREE.MeshStandardMaterial
    ['leaf_green.001']: THREE.MeshStandardMaterial
    leaf_green: THREE.MeshStandardMaterial
    ['leaf_green.002']: THREE.MeshStandardMaterial
    ['leaf_green.005']: THREE.MeshStandardMaterial
    ['tree_wood.014']: THREE.MeshStandardMaterial
    ['leaf_green.084']: THREE.MeshStandardMaterial
    ['leaf_green.085']: THREE.MeshStandardMaterial
    ['leaf_green.086']: THREE.MeshStandardMaterial
    ['leaf_green.087']: THREE.MeshStandardMaterial
    ['leaf_green.088']: THREE.MeshStandardMaterial
    ['leaf_green.089']: THREE.MeshStandardMaterial
    ['mat.tree-elm']: THREE.MeshStandardMaterial
    ['Material.132']: THREE.MeshStandardMaterial
    ['Material.052']: THREE.MeshStandardMaterial
    ['Material.131']: THREE.MeshStandardMaterial
    ['Material.053']: THREE.MeshStandardMaterial
    ['Material.004']: THREE.MeshStandardMaterial
    ['Material.114']: THREE.MeshStandardMaterial
    ['Material.141']: THREE.MeshStandardMaterial
    ['Material.098']: THREE.MeshStandardMaterial
    ['Material.140']: THREE.MeshStandardMaterial
    ['Material.099']: THREE.MeshStandardMaterial
    ['tree_wood.001']: THREE.MeshStandardMaterial
    ['leaf_green.007']: THREE.MeshStandardMaterial
    ['leaf_green.008']: THREE.MeshStandardMaterial
    ['leaf_green.009']: THREE.MeshStandardMaterial
    ['leaf_green.010']: THREE.MeshStandardMaterial
    ['leaf_green.011']: THREE.MeshStandardMaterial
    ['leaf_green.006']: THREE.MeshStandardMaterial
    ['tree_wood.002']: THREE.MeshStandardMaterial
    ['leaf_green.012']: THREE.MeshStandardMaterial
    ['leaf_green.017']: THREE.MeshStandardMaterial
    ['leaf_green.016']: THREE.MeshStandardMaterial
    ['leaf_green.015']: THREE.MeshStandardMaterial
    ['leaf_green.014']: THREE.MeshStandardMaterial
    ['leaf_green.013']: THREE.MeshStandardMaterial
    ['tree_wood.003']: THREE.MeshStandardMaterial
    ['leaf_green.019']: THREE.MeshStandardMaterial
    ['leaf_green.020']: THREE.MeshStandardMaterial
    ['leaf_green.021']: THREE.MeshStandardMaterial
    ['leaf_green.022']: THREE.MeshStandardMaterial
    ['leaf_green.023']: THREE.MeshStandardMaterial
    ['leaf_green.018']: THREE.MeshStandardMaterial
    ['tree_wood.004']: THREE.MeshStandardMaterial
    ['leaf_green.024']: THREE.MeshStandardMaterial
    ['leaf_green.029']: THREE.MeshStandardMaterial
    ['leaf_green.028']: THREE.MeshStandardMaterial
    ['leaf_green.027']: THREE.MeshStandardMaterial
    ['leaf_green.026']: THREE.MeshStandardMaterial
    ['leaf_green.025']: THREE.MeshStandardMaterial
    ['tree_wood.005']: THREE.MeshStandardMaterial
    ['leaf_green.031']: THREE.MeshStandardMaterial
    ['leaf_green.032']: THREE.MeshStandardMaterial
    ['leaf_green.033']: THREE.MeshStandardMaterial
    ['leaf_green.034']: THREE.MeshStandardMaterial
    ['leaf_green.035']: THREE.MeshStandardMaterial
    ['leaf_green.030']: THREE.MeshStandardMaterial
    ['tree_wood.006']: THREE.MeshStandardMaterial
    ['leaf_green.037']: THREE.MeshStandardMaterial
    ['leaf_green.038']: THREE.MeshStandardMaterial
    ['leaf_green.039']: THREE.MeshStandardMaterial
    ['leaf_green.040']: THREE.MeshStandardMaterial
    ['leaf_green.041']: THREE.MeshStandardMaterial
    ['leaf_green.036']: THREE.MeshStandardMaterial
    ['tree_wood.007']: THREE.MeshStandardMaterial
    ['leaf_green.042']: THREE.MeshStandardMaterial
    ['leaf_green.047']: THREE.MeshStandardMaterial
    ['leaf_green.046']: THREE.MeshStandardMaterial
    ['leaf_green.045']: THREE.MeshStandardMaterial
    ['leaf_green.044']: THREE.MeshStandardMaterial
    ['leaf_green.043']: THREE.MeshStandardMaterial
    ['tree_wood.008']: THREE.MeshStandardMaterial
    ['leaf_green.049']: THREE.MeshStandardMaterial
    ['leaf_green.050']: THREE.MeshStandardMaterial
    ['leaf_green.051']: THREE.MeshStandardMaterial
    ['leaf_green.052']: THREE.MeshStandardMaterial
    ['leaf_green.053']: THREE.MeshStandardMaterial
    ['leaf_green.048']: THREE.MeshStandardMaterial
    ['tree_wood.009']: THREE.MeshStandardMaterial
    ['leaf_green.054']: THREE.MeshStandardMaterial
    ['leaf_green.059']: THREE.MeshStandardMaterial
    ['leaf_green.058']: THREE.MeshStandardMaterial
    ['leaf_green.057']: THREE.MeshStandardMaterial
    ['leaf_green.056']: THREE.MeshStandardMaterial
    ['leaf_green.055']: THREE.MeshStandardMaterial
    ['tree_wood.015']: THREE.MeshStandardMaterial
    ['leaf_green.091']: THREE.MeshStandardMaterial
    ['leaf_green.092']: THREE.MeshStandardMaterial
    ['leaf_green.093']: THREE.MeshStandardMaterial
    ['leaf_green.094']: THREE.MeshStandardMaterial
    ['leaf_green.095']: THREE.MeshStandardMaterial
    ['leaf_green.090']: THREE.MeshStandardMaterial
    ['tree_wood.016']: THREE.MeshStandardMaterial
    ['leaf_green.096']: THREE.MeshStandardMaterial
    ['leaf_green.101']: THREE.MeshStandardMaterial
    ['leaf_green.100']: THREE.MeshStandardMaterial
    ['leaf_green.099']: THREE.MeshStandardMaterial
    ['leaf_green.098']: THREE.MeshStandardMaterial
    ['leaf_green.097']: THREE.MeshStandardMaterial
    ['tree_wood.017']: THREE.MeshStandardMaterial
    ['leaf_green.103']: THREE.MeshStandardMaterial
    ['leaf_green.104']: THREE.MeshStandardMaterial
    ['leaf_green.105']: THREE.MeshStandardMaterial
    ['leaf_green.106']: THREE.MeshStandardMaterial
    ['leaf_green.107']: THREE.MeshStandardMaterial
    ['leaf_green.102']: THREE.MeshStandardMaterial
    ['tree_wood.018']: THREE.MeshStandardMaterial
    ['leaf_green.108']: THREE.MeshStandardMaterial
    ['leaf_green.113']: THREE.MeshStandardMaterial
    ['leaf_green.112']: THREE.MeshStandardMaterial
    ['leaf_green.111']: THREE.MeshStandardMaterial
    ['leaf_green.110']: THREE.MeshStandardMaterial
    ['leaf_green.109']: THREE.MeshStandardMaterial
    ['tree_wood.019']: THREE.MeshStandardMaterial
    ['leaf_green.115']: THREE.MeshStandardMaterial
    ['leaf_green.116']: THREE.MeshStandardMaterial
    ['leaf_green.117']: THREE.MeshStandardMaterial
    ['leaf_green.118']: THREE.MeshStandardMaterial
    ['leaf_green.119']: THREE.MeshStandardMaterial
    ['leaf_green.114']: THREE.MeshStandardMaterial
    ['tree_wood.020']: THREE.MeshStandardMaterial
    ['leaf_green.120']: THREE.MeshStandardMaterial
    ['leaf_green.125']: THREE.MeshStandardMaterial
    ['leaf_green.124']: THREE.MeshStandardMaterial
    ['leaf_green.123']: THREE.MeshStandardMaterial
    ['leaf_green.122']: THREE.MeshStandardMaterial
    ['leaf_green.121']: THREE.MeshStandardMaterial
    ['tree_wood.021']: THREE.MeshStandardMaterial
    ['leaf_green.127']: THREE.MeshStandardMaterial
    ['leaf_green.128']: THREE.MeshStandardMaterial
    ['leaf_green.129']: THREE.MeshStandardMaterial
    ['leaf_green.130']: THREE.MeshStandardMaterial
    ['leaf_green.131']: THREE.MeshStandardMaterial
    ['leaf_green.126']: THREE.MeshStandardMaterial
    ['tree_wood.022']: THREE.MeshStandardMaterial
    ['leaf_green.132']: THREE.MeshStandardMaterial
    ['leaf_green.137']: THREE.MeshStandardMaterial
    ['leaf_green.136']: THREE.MeshStandardMaterial
    ['leaf_green.135']: THREE.MeshStandardMaterial
    ['leaf_green.134']: THREE.MeshStandardMaterial
    ['leaf_green.133']: THREE.MeshStandardMaterial
    ['tree_wood.023']: THREE.MeshStandardMaterial
    ['leaf_green.139']: THREE.MeshStandardMaterial
    ['leaf_green.140']: THREE.MeshStandardMaterial
    ['leaf_green.141']: THREE.MeshStandardMaterial
    ['leaf_green.142']: THREE.MeshStandardMaterial
    ['leaf_green.143']: THREE.MeshStandardMaterial
    ['leaf_green.138']: THREE.MeshStandardMaterial
    ['tree_wood.024']: THREE.MeshStandardMaterial
    ['leaf_green.144']: THREE.MeshStandardMaterial
    ['leaf_green.149']: THREE.MeshStandardMaterial
    ['leaf_green.148']: THREE.MeshStandardMaterial
    ['leaf_green.147']: THREE.MeshStandardMaterial
    ['leaf_green.146']: THREE.MeshStandardMaterial
    ['leaf_green.145']: THREE.MeshStandardMaterial
    ['tree_wood.025']: THREE.MeshStandardMaterial
    ['leaf_green.151']: THREE.MeshStandardMaterial
    ['leaf_green.152']: THREE.MeshStandardMaterial
    ['leaf_green.153']: THREE.MeshStandardMaterial
    ['leaf_green.154']: THREE.MeshStandardMaterial
    ['leaf_green.155']: THREE.MeshStandardMaterial
    ['leaf_green.150']: THREE.MeshStandardMaterial
    ['tree_wood.026']: THREE.MeshStandardMaterial
    ['leaf_green.156']: THREE.MeshStandardMaterial
    ['leaf_green.161']: THREE.MeshStandardMaterial
    ['leaf_green.160']: THREE.MeshStandardMaterial
    ['leaf_green.159']: THREE.MeshStandardMaterial
    ['leaf_green.158']: THREE.MeshStandardMaterial
    ['leaf_green.157']: THREE.MeshStandardMaterial
    ['mat.tree-elm.001']: THREE.MeshStandardMaterial
    ['mat.tree-elm.002']: THREE.MeshStandardMaterial
    ['mat.tree-elm.003']: THREE.MeshStandardMaterial
    ['mat.tree-elm.004']: THREE.MeshStandardMaterial
    ['mat.tree-elm.005']: THREE.MeshStandardMaterial
    ['mat.tree-elm.006']: THREE.MeshStandardMaterial
    ['mat.tree-elm.007']: THREE.MeshStandardMaterial
    ['mat.tree-elm.008']: THREE.MeshStandardMaterial
    ['mat.tree-elm.009']: THREE.MeshStandardMaterial
    ['mat.tree-elm.010']: THREE.MeshStandardMaterial
    ['mat.tree-elm.011']: THREE.MeshStandardMaterial
    ['mat.tree-elm.012']: THREE.MeshStandardMaterial
    ['mat.tree-elm.013']: THREE.MeshStandardMaterial
    ['Material.134']: THREE.MeshStandardMaterial
    ['Material.092']: THREE.MeshStandardMaterial
    ['Material.113']: THREE.MeshStandardMaterial
    ['Material.003']: THREE.MeshStandardMaterial
    ['Material.010']: THREE.MeshStandardMaterial
    ['Material.011']: THREE.MeshStandardMaterial
    ['Material.012']: THREE.MeshStandardMaterial
    ['Material.091']: THREE.MeshStandardMaterial
    ['Material.138']: THREE.MeshStandardMaterial
    ['Material.175']: THREE.MeshStandardMaterial
    ['Material.111']: THREE.MeshStandardMaterial
    ['Material.168']: THREE.MeshStandardMaterial
    ['Material.129']: THREE.MeshStandardMaterial
    ['Material.171']: THREE.MeshStandardMaterial
    ['Material.135']: THREE.MeshStandardMaterial
    ['Material.173']: THREE.MeshStandardMaterial
    Material: THREE.MeshStandardMaterial
    ['Material.169']: THREE.MeshStandardMaterial
    ['Material.170']: THREE.MeshStandardMaterial
    ['Material.136']: THREE.MeshStandardMaterial
    ['Material.174']: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
    ['Material.181']: THREE.MeshStandardMaterial
    ['Material.182']: THREE.MeshStandardMaterial
    ['Material.184']: THREE.MeshStandardMaterial
    ['Material.185']: THREE.MeshStandardMaterial
    ['Material.020']: THREE.MeshStandardMaterial
    ['Material.176']: THREE.MeshStandardMaterial
    ['Material.108']: THREE.MeshStandardMaterial
    ['Material.101']: THREE.MeshStandardMaterial
    ['Material.102']: THREE.MeshStandardMaterial
    ['Material.100']: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
    ['Material.049']: THREE.MeshStandardMaterial
    ['Material.050']: THREE.MeshStandardMaterial
    ['Material.051']: THREE.MeshStandardMaterial
    ['Material.097']: THREE.MeshStandardMaterial
    ['Material.112']: THREE.MeshStandardMaterial
    ['Material.164']: THREE.MeshStandardMaterial
    ['Material.163']: THREE.MeshStandardMaterial
    ['Material.162']: THREE.MeshStandardMaterial
    ['Material.161']: THREE.MeshStandardMaterial
    ['Material.167']: THREE.MeshStandardMaterial
    ['Material.166']: THREE.MeshStandardMaterial
    ['Material.165']: THREE.MeshStandardMaterial
    ['Material.130']: THREE.MeshStandardMaterial
    ['Material.172']: THREE.MeshStandardMaterial
    ['Material.019']: THREE.MeshStandardMaterial
    ['Material.021']: THREE.MeshStandardMaterial
    ['Material.144']: THREE.MeshStandardMaterial
    ['Material.145']: THREE.MeshStandardMaterial
    ['Material.146']: THREE.MeshStandardMaterial
    ['Material.142']: THREE.MeshStandardMaterial
    ['Material.143']: THREE.MeshStandardMaterial
    ['Material.110']: THREE.MeshStandardMaterial
    ['Material.109']: THREE.MeshStandardMaterial
    ['Material.104']: THREE.MeshStandardMaterial
    ['Material.155']: THREE.MeshStandardMaterial
    ['Material.186']: THREE.MeshStandardMaterial
    ['Material.107']: THREE.MeshStandardMaterial
    ['Material.106']: THREE.MeshStandardMaterial
    ['Material.105']: THREE.MeshStandardMaterial
    ['Material.147']: THREE.MeshStandardMaterial
    ['Material.149']: THREE.MeshStandardMaterial
    ['Material.150']: THREE.MeshStandardMaterial
    ['Material.148']: THREE.MeshStandardMaterial
    ['Material.005']: THREE.MeshStandardMaterial
    ['Material.177']: THREE.MeshStandardMaterial
    ['Material.178']: THREE.MeshStandardMaterial
    ['Material.179']: THREE.MeshStandardMaterial
    ['Material.139']: THREE.MeshStandardMaterial
    ['Material.006']: THREE.MeshStandardMaterial
    ['Material.180']: THREE.MeshStandardMaterial
    ['Material.126']: THREE.MeshStandardMaterial
    ['Material.127']: THREE.MeshStandardMaterial
    ['Material.128']: THREE.MeshStandardMaterial
    ['Material.133']: THREE.MeshStandardMaterial
    ['Material.093']: THREE.MeshStandardMaterial
    ['Material.094']: THREE.MeshStandardMaterial
    ['Material.187']: THREE.MeshStandardMaterial
    ['Material.188']: THREE.MeshStandardMaterial
    ['Material.189']: THREE.MeshStandardMaterial
    ['Material.190']: THREE.MeshStandardMaterial
    ['Material.191']: THREE.MeshStandardMaterial
    ['Material.192']: THREE.MeshStandardMaterial
    ['Material.193']: THREE.MeshStandardMaterial
    ['Material.194']: THREE.MeshStandardMaterial
    ['Material.195']: THREE.MeshStandardMaterial
    ['Material.196']: THREE.MeshStandardMaterial
    ['Material.197']: THREE.MeshStandardMaterial
    ['Material.198']: THREE.MeshStandardMaterial
    ['Material.199']: THREE.MeshStandardMaterial
    ['Material.200']: THREE.MeshStandardMaterial
    ['Material.201']: THREE.MeshStandardMaterial
    ['Material.202']: THREE.MeshStandardMaterial
    ['Material.203']: THREE.MeshStandardMaterial
    ['Material.204']: THREE.MeshStandardMaterial
    ['Material.205']: THREE.MeshStandardMaterial
    ['Material.206']: THREE.MeshStandardMaterial
    ['Material.207']: THREE.MeshStandardMaterial
    ['Material.208']: THREE.MeshStandardMaterial
    ['Material.209']: THREE.MeshStandardMaterial
    ['Material.210']: THREE.MeshStandardMaterial
    ['Material.211']: THREE.MeshStandardMaterial
    ['Material.212']: THREE.MeshStandardMaterial
    ['Material.213']: THREE.MeshStandardMaterial
    ['Material.214']: THREE.MeshStandardMaterial
    ['Material.215']: THREE.MeshStandardMaterial
    ['Material.216']: THREE.MeshStandardMaterial
    ['Material.217']: THREE.MeshStandardMaterial
    ['Material.218']: THREE.MeshStandardMaterial
    ['Material.219']: THREE.MeshStandardMaterial
    ['Material.220']: THREE.MeshStandardMaterial
    ['Material.221']: THREE.MeshStandardMaterial
    ['Material.222']: THREE.MeshStandardMaterial
    ['Material.223']: THREE.MeshStandardMaterial
    ['Material.224']: THREE.MeshStandardMaterial
    ['Material.225']: THREE.MeshStandardMaterial
    ['Material.226']: THREE.MeshStandardMaterial
    ['Material.227']: THREE.MeshStandardMaterial
    ['Material.228']: THREE.MeshStandardMaterial
    ['Material.229']: THREE.MeshStandardMaterial
    ['Material.230']: THREE.MeshStandardMaterial
  }
}

export interface IModelProps {
  openUI: boolean;
  openSidebar: boolean;
  setOpenSidebar: React.Dispatch<React.SetStateAction<boolean>>;
  setSidebarContent: React.Dispatch<React.SetStateAction<ISidebarContent>>;
}

export default function Model({ openUI, openSidebar, setOpenSidebar, setSidebarContent }: IModelProps) {
  const { nodes, materials } = useGLTF('/3d-model/lsw.gltf') as GLTFResult
  return (
    <group dispose={null}>
      <group position={[-57.23, 5.6, 117.26]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={0.26}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          {openUI && (
            <Html position={[-5, 15, 0]}>
              <div id="Shrine" className='rounded-lg bg-blue-700 p-2'>
                <button onClick={() => {
                  setOpenSidebar(!openSidebar)
                  setSidebarContent(lswData.Shrine)
                }} className='flex justify-center items-center text-white'><BiSearchAlt /></button>
              </div>
            </Html>
          )}
          <mesh geometry={nodes.Garden_Shrine_lambert7_0.geometry} material={materials['Material.103']} position={[-5.77, -1.43, 0]} rotation={[-Math.PI, 0.02, -Math.PI]} scale={0.13} />
        </group>
      </group>
      <group position={[0, 5.97, -12.3]} rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Fountain_Fountain_0.geometry} material={materials['Material.137']} position={[1.49, -1.18, -0.43]} scale={[1.2, 1.2, 0.94]} />
          </group>
        </group>
      </group>
      <group position={[-70.95, 5.65, 45.85]} rotation={[-Math.PI / 2, 0, 0]} scale={0.28}>
        <mesh geometry={nodes.Cylinder_0.geometry} material={materials.tree_wood} scale={[1, 1, 6.69]} />
        <mesh geometry={nodes.Icosphere_0.geometry} material={materials['leaf_green.003']} position={[0.03, 1.99, 20.57]} scale={2.44} />
        <mesh geometry={nodes.Icosphere001_0.geometry} material={materials['leaf_green.004']} position={[-12.06, 11.58, 18.51]} scale={2.44} />
        <mesh geometry={nodes.Icosphere002_0.geometry} material={materials['leaf_green.001']} position={[-12.83, -4.37, 18.68]} scale={2.44} />
        <mesh geometry={nodes.Icosphere003_0.geometry} material={materials.leaf_green} position={[13.32, 3.81, 20.57]} scale={2.44} />
        <mesh geometry={nodes.Icosphere004_0.geometry} material={materials['leaf_green.002']} position={[5.02, -8, 16.59]} scale={2.44} />
        <mesh geometry={nodes.Icosphere005_0.geometry} material={materials['leaf_green.005']} position={[1.94, 12.6, 17.61]} scale={2.44} />
      </group>
      <group position={[-17.27, 5.64, 2.22]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.05, 0.05, 0.07]}>
        <mesh geometry={nodes.Cylinder_0010.geometry} material={materials['tree_wood.014']} scale={[1, 1, 6.69]} />
        <mesh geometry={nodes.Icosphere_0010.geometry} material={materials['leaf_green.084']} position={[0.03, 1.99, 20.57]} scale={2.44} />
        <mesh geometry={nodes.Icosphere001_0010.geometry} material={materials['leaf_green.085']} position={[-12.06, 11.58, 18.51]} scale={2.44} />
        <mesh geometry={nodes.Icosphere002_0010.geometry} material={materials['leaf_green.086']} position={[-12.83, -4.37, 18.68]} scale={2.44} />
        <mesh geometry={nodes.Icosphere003_0010.geometry} material={materials['leaf_green.087']} position={[13.32, 3.81, 20.57]} scale={2.44} />
        <mesh geometry={nodes.Icosphere004_0010.geometry} material={materials['leaf_green.088']} position={[5.02, -8, 16.59]} scale={2.44} />
        <mesh geometry={nodes.Icosphere005_0010.geometry} material={materials['leaf_green.089']} position={[1.94, 12.6, 17.61]} scale={2.44} />
      </group>
      <group position={[-15.38, 5.62, 13]} rotation={[-Math.PI / 2, 0, 0]} scale={0}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes['Icosphere001_mattree-elm_0'].geometry} material={materials['mat.tree-elm']} position={[-318.77, 438.34, -322.15]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
      </group>
      <group position={[-25.96, 6.55, -52.75]} rotation={[Math.PI / 2, 0, 0]} scale={0.4}>
        <mesh geometry={nodes.Object_2009.geometry} material={nodes.Object_2009.material} position={[1.78, -0.02, -0.11]} scale={[1.65, 1, 1.24]} />
      </group>
      <group position={[-26.54, 6.55, -52.75]} rotation={[Math.PI / 2, 0, 0]} scale={0.4}>
        <group position={[1.78, -0.02, -0.11]} scale={[1.65, 1, 1.24]}>
          <mesh geometry={nodes.Object_0008.geometry} material={materials['Material.132']} />
          <mesh geometry={nodes.Object_0008_1.geometry} material={materials['Material.052']} />
        </group>
      </group>
      <group position={[-24.25, 6.56, -52.74]} rotation={[Math.PI / 2, 0, 0]} scale={0.71}>
        <group position={[-11.15, -0.03, -0.03]} scale={[0.93, 0.56, 0.7]}>
          <mesh geometry={nodes.Object_0003.geometry} material={materials['Material.131']} />
          <mesh geometry={nodes.Object_0003_1.geometry} material={materials['Material.053']} />
        </group>
      </group>
      <group position={[37.16, 6.55, 109.22]} rotation={[Math.PI / 2, 0, 0]} scale={[0.4, 1.06, 0.4]}>
        <group position={[-4.82, -8.49, -0.11]} rotation={[0, 0, Math.PI / 2]} scale={[0.86, 1, 1.24]}>
          <mesh geometry={nodes.Object_0013.geometry} material={materials['Material.004']} />
          <mesh geometry={nodes.Object_0013_1.geometry} material={materials['Material.114']} />
        </group>
      </group>
      <group position={[74.11, 6.55, -38.54]} rotation={[Math.PI / 2, 0, 0]} scale={[0.87, 0.52, 0.52]}>
        <group position={[-17.48, -3.18, -0.12]} scale={[1.81, 1.1, 1.36]}>
          <mesh geometry={nodes.Object_0002.geometry} material={materials['Material.141']} />
          <mesh geometry={nodes.Object_0002_1.geometry} material={materials['Material.098']} />
        </group>
      </group>
      <group position={[84.32, 6.54, -39.88]} rotation={[Math.PI / 2, 0, 0]} scale={[0.96, 0.57, 0.57]}>
        <group position={[-15.36, -0.53, -0.11]} scale={[1.65, 1, 1.24]}>
          <mesh geometry={nodes.Object_0004.geometry} material={materials['Material.140']} />
          <mesh geometry={nodes.Object_0004_1.geometry} material={materials['Material.099']} />
        </group>
      </group>
      <group position={[-70.95, 5.65, 52.62]} rotation={[-Math.PI / 2, 0, 0]} scale={0.28}>
        <group scale={[1, 1, 6.69]}>
          <mesh geometry={nodes.Cylinder_0001.geometry} material={materials['tree_wood.001']} position={[0.53, -0.41, 0.04]} scale={1.49} />
        </group>
        <group position={[5.02, -8, 16.59]} scale={2.44}>
          <mesh geometry={nodes.Icosphere004_0001.geometry} material={materials['leaf_green.008']} position={[1.22, -1.76, 3.42]} scale={1.49} />
        </group>
        <group position={[13.32, 3.81, 20.57]} scale={2.44}>
          <mesh geometry={nodes.Icosphere003_0001.geometry} material={materials['leaf_green.009']} position={[2.87, 0.59, 4.22]} scale={1.49} />
        </group>
        <group position={[-12.83, -4.37, 18.68]} scale={2.44}>
          <mesh geometry={nodes.Icosphere002_0001.geometry} material={materials['leaf_green.010']} position={[-2.34, -1.04, 3.84]} scale={1.49} />
        </group>
        <group position={[-12.06, 11.58, 18.51]} scale={2.44}>
          <mesh geometry={nodes.Icosphere001_0001.geometry} material={materials['leaf_green.011']} position={[-2.18, 2.14, 3.81]} scale={1.49} />
        </group>
        <group position={[0.03, 1.99, 20.57]} scale={2.44}>
          <mesh geometry={nodes.Icosphere_0001.geometry} material={materials['leaf_green.006']} position={[0.22, 0.23, 4.22]} scale={1.49} />
        </group>
        <mesh geometry={nodes.Icosphere005_0001.geometry} material={materials['leaf_green.007']} position={[1.94, 12.6, 17.61]} scale={2.44} />
      </group>
      <group position={[-70.95, 5.65, 60.33]} rotation={[-Math.PI / 2, 0, 0]} scale={0.28}>
        <mesh geometry={nodes.Cylinder_0002.geometry} material={materials['tree_wood.002']} scale={[1, 1, 6.69]} />
        <mesh geometry={nodes.Icosphere_0002.geometry} material={materials['leaf_green.012']} position={[0.03, 1.99, 20.57]} scale={2.44} />
        <mesh geometry={nodes.Icosphere001_0002.geometry} material={materials['leaf_green.017']} position={[-12.06, 11.58, 18.51]} scale={2.44} />
        <mesh geometry={nodes.Icosphere002_0002.geometry} material={materials['leaf_green.016']} position={[-12.83, -4.37, 18.68]} scale={2.44} />
        <mesh geometry={nodes.Icosphere003_0002.geometry} material={materials['leaf_green.015']} position={[13.32, 3.81, 20.57]} scale={2.44} />
        <mesh geometry={nodes.Icosphere004_0002.geometry} material={materials['leaf_green.014']} position={[5.02, -8, 16.59]} scale={2.44} />
        <mesh geometry={nodes.Icosphere005_0002.geometry} material={materials['leaf_green.013']} position={[1.94, 12.6, 17.61]} scale={2.44} />
      </group>
      <group position={[-70.95, 5.65, 68.43]} rotation={[-Math.PI / 2, 0, 0]} scale={0.28}>
        <group scale={[1, 1, 6.69]}>
          <mesh geometry={nodes.Cylinder_0003.geometry} material={materials['tree_wood.003']} position={[0.23, -0.17, 0.08]} scale={1.21} />
        </group>
        <group position={[5.02, -8, 16.59]} scale={2.44}>
          <mesh geometry={nodes.Icosphere004_0003.geometry} material={materials['leaf_green.020']} position={[0.52, -0.75, 1.63]} scale={1.21} />
        </group>
        <group position={[13.32, 3.81, 20.57]} scale={2.44}>
          <mesh geometry={nodes.Icosphere003_0003.geometry} material={materials['leaf_green.021']} position={[1.22, 0.25, 1.96]} scale={1.21} />
        </group>
        <group position={[-12.83, -4.37, 18.68]} scale={2.44}>
          <mesh geometry={nodes.Icosphere002_0003.geometry} material={materials['leaf_green.022']} position={[-1, -0.44, 1.8]} scale={1.21} />
        </group>
        <group position={[-12.06, 11.58, 18.51]} scale={2.44}>
          <mesh geometry={nodes.Icosphere001_0003.geometry} material={materials['leaf_green.023']} position={[-0.93, 0.91, 1.79]} scale={1.21} />
        </group>
        <group position={[0.03, 1.99, 20.57]} scale={2.44}>
          <mesh geometry={nodes.Icosphere_0003.geometry} material={materials['leaf_green.018']} position={[0.09, 0.1, 1.96]} scale={1.21} />
        </group>
        <mesh geometry={nodes.Icosphere005_0003.geometry} material={materials['leaf_green.019']} position={[1.94, 12.6, 17.61]} scale={2.44} />
      </group>
      <group position={[-70.95, 5.65, 77.53]} rotation={[-Math.PI / 2, 0, 0]} scale={0.28}>
        <group scale={[1, 1, 6.69]}>
          <mesh geometry={nodes.Cylinder_0004.geometry} material={materials['tree_wood.004']} position={[-0.51, 1.37, -0.06]} scale={0.68} />
        </group>
        <group position={[-12.06, 11.58, 18.51]} scale={2.44}>
          <mesh geometry={nodes.Icosphere001_0004.geometry} material={materials['leaf_green.029']} position={[1.38, -0.96, -2.61]} scale={0.68} />
        </group>
        <group position={[-12.83, -4.37, 18.68]} scale={2.44}>
          <mesh geometry={nodes.Icosphere002_0004.geometry} material={materials['leaf_green.028']} position={[1.48, 1.14, -2.63]} scale={0.68} />
        </group>
        <group position={[1.94, 12.6, 17.61]} scale={2.44}>
          <mesh geometry={nodes.Icosphere005_0004.geometry} material={materials['leaf_green.025']} position={[-0.47, -1.1, -2.49]} scale={0.68} />
        </group>
        <mesh geometry={nodes.Icosphere_0004.geometry} material={materials['leaf_green.024']} position={[-0.49, 2.72, 13.52]} scale={1.66} />
        <mesh geometry={nodes.Icosphere003_0004.geometry} material={materials['leaf_green.027']} position={[8.52, 3.96, 13.52]} scale={1.66} />
        <mesh geometry={nodes.Icosphere004_0004.geometry} material={materials['leaf_green.026']} position={[5.02, -8, 16.59]} scale={2.44} />
      </group>
      <group position={[-70.95, 5.65, 77.53]} rotation={[-Math.PI / 2, 0, 0]} scale={0.28}>
        <group scale={[1, 1, 6.69]}>
          <mesh geometry={nodes.Cylinder_0005.geometry} material={materials['tree_wood.005']} position={[-0.51, 1.37, -0.06]} scale={0.68} />
        </group>
        <group position={[1.94, 12.6, 17.61]} scale={2.44}>
          <mesh geometry={nodes.Icosphere005_0005.geometry} material={materials['leaf_green.031']} position={[-0.47, -1.1, -2.49]} scale={0.68} />
        </group>
        <group position={[-12.83, -4.37, 18.68]} scale={2.44}>
          <mesh geometry={nodes.Icosphere002_0005.geometry} material={materials['leaf_green.034']} position={[1.48, 1.14, -2.63]} scale={0.68} />
        </group>
        <group position={[-12.06, 11.58, 18.51]} scale={2.44}>
          <mesh geometry={nodes.Icosphere001_0005.geometry} material={materials['leaf_green.035']} position={[1.38, -0.96, -2.61]} scale={0.68} />
        </group>
        <mesh geometry={nodes.Icosphere004_0005.geometry} material={materials['leaf_green.032']} position={[5.02, -8, 16.59]} scale={2.44} />
        <mesh geometry={nodes.Icosphere003_0005.geometry} material={materials['leaf_green.033']} position={[8.52, 3.96, 13.52]} scale={1.66} />
        <mesh geometry={nodes.Icosphere_0005.geometry} material={materials['leaf_green.030']} position={[-0.49, 2.72, 13.52]} scale={1.66} />
      </group>
      <group position={[-70.95, 5.65, 85.16]} rotation={[-Math.PI / 2, 0, 0]} scale={0.28}>
        <group scale={[1, 1, 6.69]}>
          <mesh geometry={nodes.Cylinder_0006.geometry} material={materials['tree_wood.006']} position={[0.3, -0.79, 0.17]} scale={1.18} />
        </group>
        <group position={[1.94, 12.6, 17.61]} scale={2.44}>
          <mesh geometry={nodes.Icosphere005_0006.geometry} material={materials['leaf_green.037']} position={[0.27, 0.63, 1.78]} scale={1.18} />
        </group>
        <group position={[13.32, 3.81, 20.57]} scale={2.44}>
          <mesh geometry={nodes.Icosphere003_0006.geometry} material={materials['leaf_green.039']} position={[1.13, -0.03, 2.01]} scale={1.18} />
        </group>
        <group position={[-12.83, -4.37, 18.68]} scale={2.44}>
          <mesh geometry={nodes.Icosphere002_0006.geometry} material={materials['leaf_green.040']} position={[-0.85, -0.65, 1.86]} scale={1.18} />
        </group>
        <group position={[-12.06, 11.58, 18.51]} scale={2.44}>
          <mesh geometry={nodes.Icosphere001_0006.geometry} material={materials['leaf_green.041']} position={[-0.79, 0.55, 1.85]} scale={1.18} />
        </group>
        <group position={[0.03, 1.99, 20.57]} scale={2.44}>
          <mesh geometry={nodes.Icosphere_0006.geometry} material={materials['leaf_green.036']} position={[0.12, -0.17, 2.01]} scale={1.18} />
        </group>
        <mesh geometry={nodes.Icosphere004_0006.geometry} material={materials['leaf_green.038']} position={[5.02, -8, 16.59]} scale={2.44} />
      </group>
      <group position={[-70.95, 5.65, 92.63]} rotation={[-Math.PI / 2, 0, 0]} scale={0.28}>
        <mesh geometry={nodes.Cylinder_0007.geometry} material={materials['tree_wood.007']} scale={[1, 1, 6.69]} />
        <mesh geometry={nodes.Icosphere_0007.geometry} material={materials['leaf_green.042']} position={[0.03, 1.99, 20.57]} scale={2.44} />
        <mesh geometry={nodes.Icosphere001_0007.geometry} material={materials['leaf_green.047']} position={[-12.06, 11.58, 18.51]} scale={2.44} />
        <mesh geometry={nodes.Icosphere002_0007.geometry} material={materials['leaf_green.046']} position={[-12.83, -4.37, 18.68]} scale={2.44} />
        <mesh geometry={nodes.Icosphere003_0007.geometry} material={materials['leaf_green.045']} position={[13.32, 3.81, 20.57]} scale={2.44} />
        <mesh geometry={nodes.Icosphere004_0007.geometry} material={materials['leaf_green.044']} position={[5.02, -8, 16.59]} scale={2.44} />
        <mesh geometry={nodes.Icosphere005_0007.geometry} material={materials['leaf_green.043']} position={[1.94, 12.6, 17.61]} scale={2.44} />
      </group>
      <group position={[-70.95, 5.65, 101.39]} rotation={[-Math.PI / 2, 0, 0]} scale={0.28}>
        <group scale={[1, 1, 6.69]}>
          <mesh geometry={nodes.Cylinder_0008.geometry} material={materials['tree_wood.008']} position={[0.7, 5.14, -0.08]} scale={1.34} />
        </group>
        <group position={[5.02, -8, 16.59]} scale={2.44}>
          <mesh geometry={nodes.Icosphere004_0008.geometry} material={materials['leaf_green.050']} position={[0.99, 0.98, 2.11]} scale={1.34} />
        </group>
        <mesh geometry={nodes.Icosphere005_0008.geometry} material={materials['leaf_green.049']} position={[1.94, 12.6, 17.61]} scale={2.44} />
        <mesh geometry={nodes.Icosphere003_0008.geometry} material={materials['leaf_green.051']} position={[13.32, 3.81, 20.57]} scale={2.44} />
        <mesh geometry={nodes.Icosphere002_0008.geometry} material={materials['leaf_green.052']} position={[-16.53, -0.73, 24.56]} scale={3.28} />
        <mesh geometry={nodes.Icosphere001_0008.geometry} material={materials['leaf_green.053']} position={[-15.49, 20.69, 24.33]} scale={3.28} />
        <mesh geometry={nodes.Icosphere_0008.geometry} material={materials['leaf_green.048']} position={[0.74, 7.81, 27.09]} scale={3.28} />
      </group>
      <group position={[-70.95, 5.65, 109.37]} rotation={[-Math.PI / 2, 0, 0]} scale={0.28}>
        <group scale={[1, 1, 6.69]}>
          <mesh geometry={nodes.Cylinder_0009.geometry} material={materials['tree_wood.009']} position={[0.7, -4.59, -0.08]} scale={1.34} />
        </group>
        <group position={[5.02, -8, 16.59]} scale={2.44}>
          <mesh geometry={nodes.Icosphere004_0009.geometry} material={materials['leaf_green.056']} position={[0.99, -3, 2.11]} scale={1.34} />
        </group>
        <mesh geometry={nodes.Icosphere_0009.geometry} material={materials['leaf_green.054']} position={[0.74, -1.92, 27.09]} scale={3.28} />
        <mesh geometry={nodes.Icosphere001_0009.geometry} material={materials['leaf_green.059']} position={[-15.49, 10.96, 24.33]} scale={3.28} />
        <mesh geometry={nodes.Icosphere002_0009.geometry} material={materials['leaf_green.058']} position={[-16.53, -10.46, 24.56]} scale={3.28} />
        <mesh geometry={nodes.Icosphere003_0009.geometry} material={materials['leaf_green.057']} position={[18.58, 0.52, 27.09]} scale={3.28} />
        <mesh geometry={nodes.Icosphere005_0009.geometry} material={materials['leaf_green.055']} position={[3.3, 12.32, 23.13]} scale={3.28} />
      </group>
      <group position={[-20.57, 5.64, 2.22]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.05, 0.05, 0.07]}>
        <mesh geometry={nodes.Cylinder_0011.geometry} material={materials['tree_wood.015']} scale={[1, 1, 6.69]} />
        <mesh geometry={nodes.Icosphere005_0011.geometry} material={materials['leaf_green.091']} position={[1.94, 12.6, 17.61]} scale={2.44} />
        <mesh geometry={nodes.Icosphere004_0011.geometry} material={materials['leaf_green.092']} position={[5.02, -8, 16.59]} scale={2.44} />
        <mesh geometry={nodes.Icosphere003_0011.geometry} material={materials['leaf_green.093']} position={[13.32, 3.81, 20.57]} scale={2.44} />
        <mesh geometry={nodes.Icosphere002_0011.geometry} material={materials['leaf_green.094']} position={[-12.83, -4.37, 18.68]} scale={2.44} />
        <mesh geometry={nodes.Icosphere001_0011.geometry} material={materials['leaf_green.095']} position={[-12.06, 11.58, 18.51]} scale={2.44} />
        <mesh geometry={nodes.Icosphere_0011.geometry} material={materials['leaf_green.090']} position={[0.03, 1.99, 20.57]} scale={2.44} />
      </group>
      <group position={[-23.77, 5.64, 2.22]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.05, 0.05, 0.07]}>
        <mesh geometry={nodes.Cylinder_0012.geometry} material={materials['tree_wood.016']} scale={[1, 1, 6.69]} />
        <mesh geometry={nodes.Icosphere_0012.geometry} material={materials['leaf_green.096']} position={[0.03, 1.99, 20.57]} scale={2.44} />
        <mesh geometry={nodes.Icosphere001_0012.geometry} material={materials['leaf_green.101']} position={[-12.06, 11.58, 18.51]} scale={2.44} />
        <mesh geometry={nodes.Icosphere002_0012.geometry} material={materials['leaf_green.100']} position={[-12.83, -4.37, 18.68]} scale={2.44} />
        <mesh geometry={nodes.Icosphere003_0012.geometry} material={materials['leaf_green.099']} position={[13.32, 3.81, 20.57]} scale={2.44} />
        <mesh geometry={nodes.Icosphere004_0012.geometry} material={materials['leaf_green.098']} position={[5.02, -8, 16.59]} scale={2.44} />
        <mesh geometry={nodes.Icosphere005_0012.geometry} material={materials['leaf_green.097']} position={[1.94, 12.6, 17.61]} scale={2.44} />
      </group>
      <group position={[-26.79, 5.64, 2.22]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.05, 0.05, 0.07]}>
        <mesh geometry={nodes.Cylinder_0013.geometry} material={materials['tree_wood.017']} scale={[1, 1, 6.69]} />
        <mesh geometry={nodes.Icosphere005_0013.geometry} material={materials['leaf_green.103']} position={[1.94, 12.6, 17.61]} scale={2.44} />
        <mesh geometry={nodes.Icosphere004_0013.geometry} material={materials['leaf_green.104']} position={[5.02, -8, 16.59]} scale={2.44} />
        <mesh geometry={nodes.Icosphere003_0013.geometry} material={materials['leaf_green.105']} position={[13.32, 3.81, 20.57]} scale={2.44} />
        <mesh geometry={nodes.Icosphere002_0013.geometry} material={materials['leaf_green.106']} position={[-12.83, -4.37, 18.68]} scale={2.44} />
        <mesh geometry={nodes.Icosphere001_0013.geometry} material={materials['leaf_green.107']} position={[-12.06, 11.58, 18.51]} scale={2.44} />
        <mesh geometry={nodes.Icosphere_0013.geometry} material={materials['leaf_green.102']} position={[0.03, 1.99, 20.57]} scale={2.44} />
      </group>
      <group position={[-29.92, 5.64, 2.22]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.05, 0.05, 0.07]}>
        <mesh geometry={nodes.Cylinder_0014.geometry} material={materials['tree_wood.018']} scale={[1, 1, 6.69]} />
        <mesh geometry={nodes.Icosphere_0014.geometry} material={materials['leaf_green.108']} position={[0.03, 1.99, 20.57]} scale={2.44} />
        <mesh geometry={nodes.Icosphere001_0014.geometry} material={materials['leaf_green.113']} position={[-12.06, 11.58, 18.51]} scale={2.44} />
        <mesh geometry={nodes.Icosphere002_0014.geometry} material={materials['leaf_green.112']} position={[-12.83, -4.37, 18.68]} scale={2.44} />
        <mesh geometry={nodes.Icosphere003_0014.geometry} material={materials['leaf_green.111']} position={[13.32, 3.81, 20.57]} scale={2.44} />
        <mesh geometry={nodes.Icosphere004_0014.geometry} material={materials['leaf_green.110']} position={[5.02, -8, 16.59]} scale={2.44} />
        <mesh geometry={nodes.Icosphere005_0014.geometry} material={materials['leaf_green.109']} position={[1.94, 12.6, 17.61]} scale={2.44} />
      </group>
      <group position={[-42.47, 5.64, 2.22]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.05, 0.05, 0.07]}>
        <mesh geometry={nodes.Cylinder_0015.geometry} material={materials['tree_wood.019']} scale={[1, 1, 6.69]} />
        <mesh geometry={nodes.Icosphere005_0015.geometry} material={materials['leaf_green.115']} position={[1.94, 12.6, 17.61]} scale={2.44} />
        <mesh geometry={nodes.Icosphere004_0015.geometry} material={materials['leaf_green.116']} position={[5.02, -8, 16.59]} scale={2.44} />
        <mesh geometry={nodes.Icosphere003_0015.geometry} material={materials['leaf_green.117']} position={[13.32, 3.81, 20.57]} scale={2.44} />
        <mesh geometry={nodes.Icosphere002_0015.geometry} material={materials['leaf_green.118']} position={[-12.83, -4.37, 18.68]} scale={2.44} />
        <mesh geometry={nodes.Icosphere001_0015.geometry} material={materials['leaf_green.119']} position={[-12.06, 11.58, 18.51]} scale={2.44} />
        <mesh geometry={nodes.Icosphere_0015.geometry} material={materials['leaf_green.114']} position={[0.03, 1.99, 20.57]} scale={2.44} />
      </group>
      <group position={[-45.66, 5.64, 2.22]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.05, 0.05, 0.07]}>
        <mesh geometry={nodes.Cylinder_0016.geometry} material={materials['tree_wood.020']} scale={[1, 1, 6.69]} />
        <mesh geometry={nodes.Icosphere_0016.geometry} material={materials['leaf_green.120']} position={[0.03, 1.99, 20.57]} scale={2.44} />
        <mesh geometry={nodes.Icosphere001_0016.geometry} material={materials['leaf_green.125']} position={[-12.06, 11.58, 18.51]} scale={2.44} />
        <mesh geometry={nodes.Icosphere002_0016.geometry} material={materials['leaf_green.124']} position={[-12.83, -4.37, 18.68]} scale={2.44} />
        <mesh geometry={nodes.Icosphere003_0016.geometry} material={materials['leaf_green.123']} position={[13.32, 3.81, 20.57]} scale={2.44} />
        <mesh geometry={nodes.Icosphere004_0016.geometry} material={materials['leaf_green.122']} position={[5.02, -8, 16.59]} scale={2.44} />
        <mesh geometry={nodes.Icosphere005_0016.geometry} material={materials['leaf_green.121']} position={[1.94, 12.6, 17.61]} scale={2.44} />
      </group>
      <group position={[-48.85, 5.64, 2.22]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.05, 0.05, 0.07]}>
        <mesh geometry={nodes.Cylinder_0017.geometry} material={materials['tree_wood.021']} scale={[1, 1, 6.69]} />
        <mesh geometry={nodes.Icosphere005_0017.geometry} material={materials['leaf_green.127']} position={[1.94, 12.6, 17.61]} scale={2.44} />
        <mesh geometry={nodes.Icosphere004_0017.geometry} material={materials['leaf_green.128']} position={[5.02, -8, 16.59]} scale={2.44} />
        <mesh geometry={nodes.Icosphere003_0017.geometry} material={materials['leaf_green.129']} position={[13.32, 3.81, 20.57]} scale={2.44} />
        <mesh geometry={nodes.Icosphere002_0017.geometry} material={materials['leaf_green.130']} position={[-12.83, -4.37, 18.68]} scale={2.44} />
        <mesh geometry={nodes.Icosphere001_0017.geometry} material={materials['leaf_green.131']} position={[-12.06, 11.58, 18.51]} scale={2.44} />
        <mesh geometry={nodes.Icosphere_0017.geometry} material={materials['leaf_green.126']} position={[0.03, 1.99, 20.57]} scale={2.44} />
      </group>
      <group position={[-52.13, 5.64, 2.22]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.05, 0.05, 0.07]}>
        <mesh geometry={nodes.Cylinder_0018.geometry} material={materials['tree_wood.022']} scale={[1, 1, 6.69]} />
        <mesh geometry={nodes.Icosphere_0018.geometry} material={materials['leaf_green.132']} position={[0.03, 1.99, 20.57]} scale={2.44} />
        <mesh geometry={nodes.Icosphere001_0018.geometry} material={materials['leaf_green.137']} position={[-12.06, 11.58, 18.51]} scale={2.44} />
        <mesh geometry={nodes.Icosphere002_0018.geometry} material={materials['leaf_green.136']} position={[-12.83, -4.37, 18.68]} scale={2.44} />
        <mesh geometry={nodes.Icosphere003_0018.geometry} material={materials['leaf_green.135']} position={[13.32, 3.81, 20.57]} scale={2.44} />
        <mesh geometry={nodes.Icosphere004_0018.geometry} material={materials['leaf_green.134']} position={[5.02, -8, 16.59]} scale={2.44} />
        <mesh geometry={nodes.Icosphere005_0018.geometry} material={materials['leaf_green.133']} position={[1.94, 12.6, 17.61]} scale={2.44} />
      </group>
      <group position={[-55.34, 5.64, 2.22]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.05, 0.05, 0.07]}>
        <mesh geometry={nodes.Cylinder_0019.geometry} material={materials['tree_wood.023']} scale={[1, 1, 6.69]} />
        <mesh geometry={nodes.Icosphere005_0019.geometry} material={materials['leaf_green.139']} position={[1.94, 12.6, 17.61]} scale={2.44} />
        <mesh geometry={nodes.Icosphere004_0019.geometry} material={materials['leaf_green.140']} position={[5.02, -8, 16.59]} scale={2.44} />
        <mesh geometry={nodes.Icosphere003_0019.geometry} material={materials['leaf_green.141']} position={[13.32, 3.81, 20.57]} scale={2.44} />
        <mesh geometry={nodes.Icosphere002_0019.geometry} material={materials['leaf_green.142']} position={[-12.83, -4.37, 18.68]} scale={2.44} />
        <mesh geometry={nodes.Icosphere001_0019.geometry} material={materials['leaf_green.143']} position={[-12.06, 11.58, 18.51]} scale={2.44} />
        <mesh geometry={nodes.Icosphere_0019.geometry} material={materials['leaf_green.138']} position={[0.03, 1.99, 20.57]} scale={2.44} />
      </group>
      <group position={[-58.53, 5.64, 2.22]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.05, 0.05, 0.07]}>
        <mesh geometry={nodes.Cylinder_0020.geometry} material={materials['tree_wood.024']} scale={[1, 1, 6.69]} />
        <mesh geometry={nodes.Icosphere_0020.geometry} material={materials['leaf_green.144']} position={[0.03, 1.99, 20.57]} scale={2.44} />
        <mesh geometry={nodes.Icosphere001_0020.geometry} material={materials['leaf_green.149']} position={[-12.06, 11.58, 18.51]} scale={2.44} />
        <mesh geometry={nodes.Icosphere002_0020.geometry} material={materials['leaf_green.148']} position={[-12.83, -4.37, 18.68]} scale={2.44} />
        <mesh geometry={nodes.Icosphere003_0020.geometry} material={materials['leaf_green.147']} position={[13.32, 3.81, 20.57]} scale={2.44} />
        <mesh geometry={nodes.Icosphere004_0020.geometry} material={materials['leaf_green.146']} position={[5.02, -8, 16.59]} scale={2.44} />
        <mesh geometry={nodes.Icosphere005_0020.geometry} material={materials['leaf_green.145']} position={[1.94, 12.6, 17.61]} scale={2.44} />
      </group>
      <group position={[-35.52, 5.64, -17.91]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.08, 0.08, 0.12]}>
        <mesh geometry={nodes.Cylinder_0021.geometry} material={materials['tree_wood.025']} scale={[1, 1, 6.69]} />
        <mesh geometry={nodes.Icosphere005_0021.geometry} material={materials['leaf_green.151']} position={[1.94, 12.6, 17.61]} scale={2.44} />
        <mesh geometry={nodes.Icosphere004_0021.geometry} material={materials['leaf_green.152']} position={[5.02, -8, 16.59]} scale={2.44} />
        <mesh geometry={nodes.Icosphere003_0021.geometry} material={materials['leaf_green.153']} position={[13.32, 3.81, 20.57]} scale={2.44} />
        <mesh geometry={nodes.Icosphere002_0021.geometry} material={materials['leaf_green.154']} position={[-12.83, -4.37, 18.68]} scale={2.44} />
        <mesh geometry={nodes.Icosphere001_0021.geometry} material={materials['leaf_green.155']} position={[-12.06, 11.58, 18.51]} scale={2.44} />
        <mesh geometry={nodes.Icosphere_0021.geometry} material={materials['leaf_green.150']} position={[0.03, 1.99, 20.57]} scale={2.44} />
      </group>
      <group position={[53.65, 5.35, -26.27]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.17, 0.17, 0.26]}>
        <mesh geometry={nodes.Cylinder_0022.geometry} material={materials['tree_wood.026']} scale={[1, 1, 6.69]} />
        <mesh geometry={nodes.Icosphere_0022.geometry} material={materials['leaf_green.156']} position={[0.03, 1.99, 20.57]} scale={2.44} />
        <mesh geometry={nodes.Icosphere001_0022.geometry} material={materials['leaf_green.161']} position={[-12.06, 11.58, 18.51]} scale={2.44} />
        <mesh geometry={nodes.Icosphere002_0022.geometry} material={materials['leaf_green.160']} position={[-12.83, -4.37, 18.68]} scale={2.44} />
        <mesh geometry={nodes.Icosphere003_0022.geometry} material={materials['leaf_green.159']} position={[13.32, 3.81, 20.57]} scale={2.44} />
        <mesh geometry={nodes.Icosphere004_0022.geometry} material={materials['leaf_green.158']} position={[5.02, -8, 16.59]} scale={2.44} />
        <mesh geometry={nodes.Icosphere005_0022.geometry} material={materials['leaf_green.157']} position={[1.94, 12.6, 17.61]} scale={2.44} />
      </group>
      <group position={[-15.38, 5.62, 19.46]} rotation={[-Math.PI / 2, 0, 0]} scale={0}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes['Icosphere001_mattree-elm_0001'].geometry} material={materials['mat.tree-elm.001']} position={[-318.77, 438.34, -322.15]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
      </group>
      <group position={[-15.38, 5.62, 25.38]} rotation={[-Math.PI / 2, 0, 0]} scale={0}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes['Icosphere001_mattree-elm_0002'].geometry} material={materials['mat.tree-elm.002']} position={[-318.77, 438.34, -322.15]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
      </group>
      <group position={[-15.38, 5.62, 31.89]} rotation={[-Math.PI / 2, 0, 0]} scale={0}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes['Icosphere001_mattree-elm_0003'].geometry} material={materials['mat.tree-elm.003']} position={[-318.77, 438.34, -322.15]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
      </group>
      <group position={[-15.38, 5.62, 38.57]} rotation={[-Math.PI / 2, 0, 0]} scale={0}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes['Icosphere001_mattree-elm_0004'].geometry} material={materials['mat.tree-elm.004']} position={[-318.77, 438.34, -322.15]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
      </group>
      <group position={[-15.38, 5.62, 44.63]} rotation={[-Math.PI / 2, 0, 0]} scale={0}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes['Icosphere001_mattree-elm_0005'].geometry} material={materials['mat.tree-elm.005']} position={[-318.77, 438.34, -322.15]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
      </group>
      <group position={[-15.38, 5.62, 51.4]} rotation={[-Math.PI / 2, 0, 0]} scale={0}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes['Icosphere001_mattree-elm_0006'].geometry} material={materials['mat.tree-elm.006']} position={[-318.77, 438.34, -322.15]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
      </group>
      <group position={[-15.38, 5.62, 57.54]} rotation={[-Math.PI / 2, 0, 0]} scale={0}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes['Icosphere001_mattree-elm_0007'].geometry} material={materials['mat.tree-elm.007']} position={[-318.77, 438.34, -322.15]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
      </group>
      <group position={[-15.38, 5.62, 65.45]} rotation={[-Math.PI / 2, 0, 0]} scale={0}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes['Icosphere001_mattree-elm_0008'].geometry} material={materials['mat.tree-elm.008']} position={[-318.77, 438.34, -322.15]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
      </group>
      <group position={[-15.38, 5.62, 71.92]} rotation={[-Math.PI / 2, 0, 0]} scale={0}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes['Icosphere001_mattree-elm_0009'].geometry} material={materials['mat.tree-elm.009']} position={[-318.77, 438.34, -322.15]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
      </group>
      <group position={[-15.38, 5.62, 78.86]} rotation={[-Math.PI / 2, 0, 0]} scale={0}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes['Icosphere001_mattree-elm_0010'].geometry} material={materials['mat.tree-elm.010']} position={[-318.77, 438.34, -322.15]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
      </group>
      <group position={[-15.38, 5.62, 86.16]} rotation={[-Math.PI / 2, 0, 0]} scale={0}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes['Icosphere001_mattree-elm_0011'].geometry} material={materials['mat.tree-elm.011']} position={[-318.77, 438.34, -322.16]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
      </group>
      <group position={[-15.38, 5.62, 93.73]} rotation={[-Math.PI / 2, 0, 0]} scale={0}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes['Icosphere001_mattree-elm_0012'].geometry} material={materials['mat.tree-elm.012']} position={[-318.77, 438.34, -322.16]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
      </group>
      <group position={[-15.38, 5.62, 102.99]} rotation={[-Math.PI / 2, 0, 0]} scale={0}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes['Icosphere001_mattree-elm_0013'].geometry} material={materials['mat.tree-elm.013']} position={[-318.77, 438.34, -322.15]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
      </group>
      <group position={[-34.13, 7.53, -34.09]} scale={[2.93, 1.42, 1.39]}>
        {openUI && (
          <Html position={[5, 8, 0]}>
            <div id="MEP_IEP" className='rounded-lg bg-blue-700 p-2'>
              <button onClick={() => {
                  setOpenSidebar(!openSidebar)
                  setSidebarContent(lswData.MEP_IEP_Building)
                }} className='flex justify-center items-center text-white'><BiSearchAlt /></button>
            </div>
          </Html>
        )}
        <mesh geometry={nodes.Cube003_1.geometry} material={materials['Material.134']} />
        <mesh geometry={nodes.Cube003_2.geometry} material={materials['Material.092']} />
      </group>
      <group position={[-30.13, 6.06, -14.44]} scale={[3.68, 0.57, 0.57]}>
        {openUI && (
          <Html position={[-2, 12, 0]}>
            <div id="Computer" className='rounded-lg bg-blue-700 p-2'>
              <button onClick={() => {
                  setOpenSidebar(!openSidebar)
                  setSidebarContent(lswData.Computer_Building)
                }} className='flex justify-center items-center text-white'><BiSearchAlt /></button>
            </div>
          </Html>
        )}
        <mesh geometry={nodes.Cube019_1.geometry} material={materials['Material.113']} />
        <mesh geometry={nodes.Cube019_2.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Cube019_3.geometry} material={materials['Material.010']} />
        <mesh geometry={nodes.Cube019_4.geometry} material={materials['Material.011']} />
        <mesh geometry={nodes.Cube019_5.geometry} material={materials['Material.012']} />
        <mesh geometry={nodes.Cube019_6.geometry} material={materials['Material.091']} />
      </group>
      <group position={[56.63, 6.56, -18.89]} scale={[1.02, 0.96, 0.96]}>
        <mesh geometry={nodes.Cube022_1.geometry} material={materials['Material.138']} />
        <mesh geometry={nodes.Cube022_2.geometry} material={materials['Material.175']} />
      </group>
      <group position={[-69.41, 6.67, -22.43]} rotation={[0, Math.PI / 2, 0]} scale={[6.79, 1.11, 2.91]}>
        {openUI && (
          <Html position={[0, 3.2, 0]}>
            <div id="Library" className='rounded-lg bg-blue-700 p-2'>
              <button onClick={() => {
                  setOpenSidebar(!openSidebar)
                  setSidebarContent(lswData.Library)
                }} className='flex justify-center items-center text-white'><BiSearchAlt /></button>
            </div>
          </Html>
        )}
        <mesh geometry={nodes.Cube005.geometry} material={materials['Material.111']} />
        <mesh geometry={nodes.Cube005_1.geometry} material={materials['Material.168']} />
      </group>
      <group position={[-71.97, 6.65, -52.93]} scale={[8.31, 1.11, 1.35]}>
        {openUI && (
          <Html position={[0, 3.2, 0]}>
            <div id="Audiovisual_room" className='rounded-lg bg-blue-700 p-2'>
              <button onClick={() => {
                  setOpenSidebar(!openSidebar)
                  setSidebarContent(lswData.Audiovisual_Room)
                }} className='flex justify-center items-center text-white'><BiSearchAlt /></button>
            </div>
          </Html>
        )}
        <mesh geometry={nodes.Cube007_1.geometry} material={materials['Material.129']} />
        <mesh geometry={nodes.Cube007_2.geometry} material={materials['Material.171']} />
      </group>
      <group position={[-12.81, 7.06, -48.16]} scale={[6.65, 1.54, 6.25]}>
        {openUI && (
          <Html position={[0, 3, 0]}>
            <div id="Faculty_of_art" className='rounded-lg bg-blue-700 p-2'>
              <button onClick={() => {
                  setOpenSidebar(!openSidebar)
                  setSidebarContent(lswData.Faculty_of_art)
                }} className='flex justify-center items-center text-white'><BiSearchAlt /></button>
            </div>
          </Html>
        )}
        <mesh geometry={nodes.Cube009_1.geometry} material={materials['Material.135']} />
        <mesh geometry={nodes.Cube009_2.geometry} material={materials['Material.173']} />
      </group>
      <group position={[-69.37, 7.34, -12.38]} scale={[-2.69, -1.77, -1.5]}>
        {openUI && (
          <Html position={[0, -1.6, 0]}>
            <div id="WorldClass" className='rounded-lg bg-blue-700 p-2'>
              <button onClick={() => {
                  setOpenSidebar(!openSidebar)
                  setSidebarContent(lswData.WorldClass)
                }} className='flex justify-center items-center text-white'><BiSearchAlt /></button>
            </div>
          </Html>
        )}
        <mesh geometry={nodes.Cube011_1.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cube011_2.geometry} material={materials['Material.169']} />
        <mesh geometry={nodes.Cube011_3.geometry} material={materials['Material.170']} />
      </group>
      <group position={[26.35, 9.17, -34.13]} rotation={[-Math.PI, 0, 0]} scale={[20.8, 3.09, 2.02]}>
        {openUI && (
          <Html position={[0.1, -2.3, 0]}>
            <div id="Social_Study_Building" className='rounded-lg bg-blue-700 p-2'>
              <button onClick={() => {
                  setOpenSidebar(!openSidebar)
                  setSidebarContent(lswData.Social_Study_Building)
                }} className='flex justify-center items-center text-white'><BiSearchAlt /></button>
            </div>
          </Html>
        )}
        <mesh geometry={nodes.Cube012_1.geometry} material={materials['Material.136']} />
        <mesh geometry={nodes.Cube012_2.geometry} material={materials['Material.174']} />
      </group>
      <group position={[2.25, 10.78, 25.3]} rotation={[0, Math.PI / 2, 0]} scale={[24.09, 4.82, 2.53]}>
        {openUI && (
          <Html position={[0, 2, 0]}>
            <div id="100years" className='rounded-lg bg-blue-700 p-2'>
              <button onClick={() => {
                  setOpenSidebar(!openSidebar)
                  setSidebarContent(lswData.One_hundred_years_buildings)
                }} className='flex justify-center items-center text-white'><BiSearchAlt /></button>
            </div>
          </Html>
        )}
        <mesh geometry={nodes.Cube013_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Cube013_2.geometry} material={materials['Material.181']} />
        <mesh geometry={nodes.Cube013_3.geometry} material={materials['Material.182']} />
        <mesh geometry={nodes.Cube013_4.geometry} material={materials['Material.184']} />
        <mesh geometry={nodes.Cube013_5.geometry} material={materials['Material.185']} />
      </group>
      <group position={[15.31, 9.88, 107.9]} rotation={[Math.PI, 0, Math.PI]} scale={[16.54, 4, 1.69]}>
        {openUI && (
          <Html position={[0, 1.6, 0]}>
            <div id="Fourth_building" className='rounded-lg bg-blue-700 p-2'>
              <button onClick={() => {
                  setOpenSidebar(!openSidebar)
                  setSidebarContent(lswData.Fourth_Building)
                }} className='flex justify-center items-center text-white'><BiSearchAlt /></button>
            </div>
          </Html>
        )}
        <mesh geometry={nodes.Cube006_1.geometry} material={materials['Material.020']} />
        <mesh geometry={nodes.Cube006_2.geometry} material={materials['Material.176']} />
      </group>
      <mesh geometry={nodes.Cube019.geometry} material={materials['Material.108']} position={[8.57, 1.63, 32.37]} scale={[90.13, 3.94, 91.18]} />
      <mesh geometry={nodes.Cube022.geometry} material={materials['Material.101']} position={[-30.85, 5.62, 117.47]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-14.83, -0.07, -2.47]} />
      <mesh geometry={nodes.Cylinder001.geometry} material={materials['Material.102']} position={[-17.3, 6.34, 119.15]} rotation={[Math.PI, 0, Math.PI]} scale={[0.04, 0.77, 0.01]} />
      <mesh geometry={nodes.Cube024.geometry} material={materials['Material.100']} position={[-11.97, 5.62, 66.09]} rotation={[0, -Math.PI / 2, 0]} scale={[-62.63, -0.07, -1.49]} />
      <mesh geometry={nodes.Cube023.geometry} material={materials['Material.002']} position={[-36.98, 5.57, 59.56]} rotation={[-Math.PI, 0, 0]} scale={[23.1, 0.03, 55.43]} />
      <mesh geometry={nodes.ทรงกระบอก001.geometry} material={materials['Material.049']} position={[9.96, 8.09, 113.01]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[1.67, 1.1, 1.52]} />
      <mesh geometry={nodes.Cube025.geometry} material={materials['Material.050']} position={[7.99, 7.93, 117.45]} rotation={[0.22, -1.57, 0]} scale={[1.45, 0.47, 2.47]} />
      <mesh geometry={nodes.ทรงกระบอก002.geometry} material={materials['Material.051']} position={[-12.33, 7.49, 116.81]} rotation={[Math.PI / 2, 0, 0]} scale={1.1} />
      <mesh geometry={nodes.ทรงกระบอก003.geometry} material={materials['Material.097']} position={[-12.33, 7.49, 102.1]} rotation={[Math.PI / 2, 0, 0]} scale={1.1} />
      <mesh geometry={nodes.Cube091.geometry} material={materials['Material.112']} position={[-36.67, 5.74, 1.89]} scale={[-3.72, -0.07, -1.49]} />
      <mesh geometry={nodes.Cube092.geometry} material={materials['Material.164']} position={[-61.15, 5.69, 14.79]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.12, -0.02, -0.56]} />
      <mesh geometry={nodes.Cube093.geometry} material={materials['Material.163']} position={[-61.15, 5.69, 18.39]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.12, -0.02, -0.56]} />
      <mesh geometry={nodes.Cube094.geometry} material={materials['Material.162']} position={[-61.15, 5.69, 21.52]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.12, -0.02, -0.56]} />
      <mesh geometry={nodes.Cube095.geometry} material={materials['Material.161']} position={[-60.93, 5.69, 24.8]} rotation={[0, -Math.PI / 2, 0]} scale={[-0.12, -0.02, -0.56]} />
      <mesh geometry={nodes.Cube096.geometry} material={materials['Material.167']} position={[-61.3, 6.09, 5.34]} scale={[-0.01, -0.6, -0.01]} />
      <mesh geometry={nodes.Cube097.geometry} material={materials['Material.166']} position={[-61.3, 6.09, 8.08]} scale={[-0.01, -0.6, -0.01]} />
      <mesh geometry={nodes.Cube098.geometry} material={materials['Material.165']} position={[-61.3, 6.09, 11.04]} scale={[-0.01, -0.6, -0.01]} />
      <group position={[-50.28, 6.4, -52.93]} scale={[9.81, 0.85, 1.35]}>
        {openUI && (
          <Html position={[0, 3.5, 0]}>
            <div id="Lab" className='rounded-lg bg-blue-700 p-2'>
              <button onClick={() => {
                  setOpenSidebar(!openSidebar)
                  setSidebarContent(lswData.Lab)
                }} className='flex justify-center items-center text-white'><BiSearchAlt /></button>
            </div>
          </Html>
        )}
        <mesh geometry={nodes.Cube100.geometry} material={materials['Material.130']} />
        <mesh geometry={nodes.Cube100_1.geometry} material={materials['Material.172']} />
      </group>
      <mesh geometry={nodes.Cylinder016.geometry} material={materials['Material.019']} position={[0.07, 8.17, 75.17]} rotation={[0, Math.PI / 2, 0]} scale={[0.04, 2.76, 0.02]} />
      <mesh geometry={nodes.Cylinder024.geometry} material={materials['Material.021']} position={[0.39, 8.43, 102.89]} scale={[0.1, 3.45, 0.12]} />
      <mesh geometry={nodes.ลูกบาศก์007.geometry} material={materials['Material.144']} position={[35.88, 5.94, -15.77]} scale={[0.15, 0.03, 0.77]} />
      <mesh geometry={nodes.ลูกบาศก์005.geometry} material={materials['Material.145']} position={[32.62, 5.94, -8.51]} scale={[0.3, 0.03, 1.16]} />
      <mesh geometry={nodes.ลูกบาศก์004.geometry} material={materials['Material.146']} position={[34.4, 5.94, -8.05]} scale={[0.32, 0.03, 1.24]} />
      <mesh geometry={nodes.ลูกบาศก์003.geometry} material={materials['Material.142']} position={[50.63, 5.94, -8.04]} scale={[0.32, 0.03, 1.24]} />
      <mesh geometry={nodes.ลูกบาศก์001.geometry} material={materials['Material.143']} position={[43.4, 5.94, -15.77]} scale={[0.15, 0.03, 0.77]} />
      <mesh geometry={nodes.Cylinder042.geometry} material={materials['Material.110']} position={[-62.15, 7.03, 20.46]} rotation={[Math.PI, 0, Math.PI]} scale={[0.01, 1.52, 0.02]} />
      <mesh geometry={nodes.Cylinder046.geometry} material={materials['Material.109']} position={[-60.67, 7.73, 38.94]} rotation={[0, Math.PI / 2, 0]} scale={[0.1, 2, 0.03]} />
      <mesh geometry={nodes.Cube103.geometry} material={materials['Material.104']} position={[-69.42, 5.66, 76.81]} scale={[9.12, 0.1, 38.15]} />
      <group position={[-15.21, 5.92, 1.79]} rotation={[Math.PI, 0, Math.PI]} scale={[0.03, 0.03, 0.01]}>
        <mesh geometry={nodes.Cube049.geometry} material={materials['Material.155']} />
        <mesh geometry={nodes.Cube049_1.geometry} material={materials['Material.186']} />
      </group>
      <mesh geometry={nodes.Cube064.geometry} material={materials['Material.107']} position={[-64.92, 5.93, 85.68]} scale={[0.69, 0.39, 0.56]} />
      <mesh geometry={nodes.Cube062.geometry} material={materials['Material.106']} position={[-64.92, 5.93, 99.39]} scale={[0.69, 0.39, 0.56]} />
      <mesh geometry={nodes.Cube063.geometry} material={materials['Material.105']} position={[-64.92, 5.93, 113.2]} scale={[0.69, 0.39, 0.56]} />
      <mesh geometry={nodes.ลูกบาศก์002.geometry} material={materials['Material.147']} position={[35.88, 5.94, -11.7]} scale={[0.15, 0.03, 0.77]} />
      <mesh geometry={nodes.ลูกบาศก์006.geometry} material={materials['Material.149']} position={[43.4, 5.94, -11.7]} scale={[0.15, 0.03, 0.77]} />
      <mesh geometry={nodes.ลูกบาศก์008.geometry} material={materials['Material.150']} position={[43.4, 5.94, -7.63]} scale={[0.15, 0.03, 0.77]} />
      <mesh geometry={nodes.ลูกบาศก์009.geometry} material={materials['Material.148']} position={[35.88, 5.94, -7.63]} scale={[0.15, 0.03, 0.77]} />
      <group position={[42.77, 7.45, -9.27]} rotation={[0, Math.PI / 2, 0]} scale={[-8.81, -1.87, -12.58]}>
        <mesh geometry={nodes.ลูกบาศก์016.geometry} material={materials['Material.005']} />
        {openUI && (
          <>
            <Html position={[0, -3, 0]}>
              <div id="Food_Hall" className='rounded-lg bg-blue-700 p-2'>
                <button onClick={() => {
                  setOpenSidebar(!openSidebar)
                  setSidebarContent(lswData.Food_Hall)
                }} className='flex justify-center items-center text-white'><BiSearchAlt /></button>
              </div>
            </Html>
            <Html position={[0, -3, 2.5]}>
              <div id="Meeting_Hall" className='rounded-lg bg-blue-700 p-2'>
                <button onClick={() => {
                  setOpenSidebar(!openSidebar)
                  setSidebarContent(lswData.Meeting_Hall)
                }} className='flex justify-center items-center text-white'><BiSearchAlt /></button>
              </div>
            </Html>
            <Html position={[0, -4.5, -2.3]}>
              <div id="Art" className='rounded-lg bg-blue-700 p-2'>
                <button onClick={() => {
                  setOpenSidebar(!openSidebar)
                  setSidebarContent(lswData.Art_Building)
                }} className='flex justify-center items-center text-white'><BiSearchAlt /></button>
              </div>
            </Html>
            <Html position={[-1.85, -1.5, -2.1]}>
              <div id="Agriculture_building" className='rounded-lg bg-blue-700 p-2'>
                <button onClick={() => {
                  setOpenSidebar(!openSidebar)
                  setSidebarContent(lswData.Agriculture_Building)
                }} className='flex justify-center items-center text-white'><BiSearchAlt /></button>
              </div>
            </Html>
          </>
        )}
        <mesh geometry={nodes.ลูกบาศก์016_1.geometry} material={materials['Material.177']} />
        <mesh geometry={nodes.ลูกบาศก์016_2.geometry} material={materials['Material.178']} />
        <mesh geometry={nodes.ลูกบาศก์016_3.geometry} material={materials['Material.179']} />
      </group>
      <mesh geometry={nodes.Cube001.geometry} material={materials['Material.139']} position={[68.04, 6.68, -25.86]} scale={[7.1, 1.2, 4.71]} />
      <group position={[28.24, 9.11, 67.04]} rotation={[Math.PI, 0, Math.PI]} scale={[11.79, 3.59, 7.69]}>
        {openUI && (
          <Html position={[0, 2.7, 0]}>
            <div id="Sport_building" className='rounded-lg bg-blue-700 p-2'>
              <button onClick={() => {
                  setOpenSidebar(!openSidebar)
                  setSidebarContent(lswData.Sport_building)
                }} className='flex justify-center items-center text-white'><BiSearchAlt /></button>
            </div>
          </Html>
        )}
        <mesh geometry={nodes.Cube051.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Cube051_1.geometry} material={materials['Material.180']} />
      </group>
      <mesh geometry={nodes.Cube003.geometry} material={materials['Material.126']} position={[-45.84, 5.58, -18.03]} scale={[14.29, 0.01, 0.76]} />
      <mesh geometry={nodes.Cube069.geometry} material={materials['Material.127']} position={[-74.51, 6.21, -34.54]} rotation={[0, Math.PI / 2, 0]} scale={[2.07, 0.77, 2.01]} />
      <mesh geometry={nodes.Cube077.geometry} material={materials['Material.128']} position={[-76.56, 6.57, -50.84]} scale={[0.03, 1.13, 0.03]} />
      <group position={[-62.21, 6.75, -36.07]} scale={[0.07, 1.45, 0.07]}>
        {openUI && (
          <Html position={[170, 5.3, 50]}>
            <div id="Science_building" className='rounded-lg bg-blue-700 p-2'>
              <button onClick={() => {
                  setOpenSidebar(!openSidebar)
                  setSidebarContent(lswData.Science_building)
                }} className='flex justify-center items-center text-white'><BiSearchAlt /></button>
            </div>
          </Html>
        )}
        <mesh geometry={nodes.Cube072.geometry} material={materials['Material.133']} />
        <mesh geometry={nodes.Cube072_1.geometry} material={materials['Material.093']} />
        <mesh geometry={nodes.Cube072_2.geometry} material={materials['Material.094']} />
      </group>
      <group position={[-15.21, 5.92, 1.79]} rotation={[Math.PI, 0, Math.PI]} scale={[0.03, 0.03, 0.01]}>
        <mesh geometry={nodes.Cube023_1.geometry} material={materials['Material.187']} />
        <mesh geometry={nodes.Cube023_2.geometry} material={materials['Material.188']} />
      </group>
      <group position={[-18.55, 5.92, 1.79]} rotation={[Math.PI, 0, Math.PI]} scale={[0.03, 0.03, 0.01]}>
        <mesh geometry={nodes.Cube024_1.geometry} material={materials['Material.189']} />
        <mesh geometry={nodes.Cube024_2.geometry} material={materials['Material.190']} />
      </group>
      <group position={[-21.9, 5.92, 1.79]} rotation={[Math.PI, 0, Math.PI]} scale={[0.03, 0.03, 0.01]}>
        <mesh geometry={nodes.Cube026_1.geometry} material={materials['Material.191']} />
        <mesh geometry={nodes.Cube026_2.geometry} material={materials['Material.192']} />
      </group>
      <group position={[-24.82, 5.92, 1.79]} rotation={[Math.PI, 0, Math.PI]} scale={[0.03, 0.03, 0.01]}>
        <mesh geometry={nodes.Cube028_1.geometry} material={materials['Material.193']} />
        <mesh geometry={nodes.Cube028_2.geometry} material={materials['Material.194']} />
      </group>
      <group position={[-27.92, 5.92, 1.79]} rotation={[Math.PI, 0, Math.PI]} scale={[0.03, 0.03, 0.01]}>
        <mesh geometry={nodes.Cube029_1.geometry} material={materials['Material.195']} />
        <mesh geometry={nodes.Cube029_2.geometry} material={materials['Material.196']} />
      </group>
      <group position={[-43.62, 5.92, 1.79]} rotation={[Math.PI, 0, Math.PI]} scale={[0.03, 0.03, 0.01]}>
        <mesh geometry={nodes.Cube030_1.geometry} material={materials['Material.197']} />
        <mesh geometry={nodes.Cube030_2.geometry} material={materials['Material.198']} />
      </group>
      <group position={[-46.87, 5.92, 1.79]} rotation={[Math.PI, 0, Math.PI]} scale={[0.03, 0.03, 0.01]}>
        <mesh geometry={nodes.Cube031_1.geometry} material={materials['Material.199']} />
        <mesh geometry={nodes.Cube031_2.geometry} material={materials['Material.200']} />
      </group>
      <group position={[-50.14, 5.92, 1.79]} rotation={[Math.PI, 0, Math.PI]} scale={[0.03, 0.03, 0.01]}>
        <mesh geometry={nodes.Cube032_1.geometry} material={materials['Material.201']} />
        <mesh geometry={nodes.Cube032_2.geometry} material={materials['Material.202']} />
      </group>
      <group position={[-53.32, 5.92, 1.79]} rotation={[Math.PI, 0, Math.PI]} scale={[0.03, 0.03, 0.01]}>
        <mesh geometry={nodes.Cube033_1.geometry} material={materials['Material.203']} />
        <mesh geometry={nodes.Cube033_2.geometry} material={materials['Material.204']} />
      </group>
      <group position={[-56.63, 5.92, 1.79]} rotation={[Math.PI, 0, Math.PI]} scale={[0.03, 0.03, 0.01]}>
        <mesh geometry={nodes.Cube034_1.geometry} material={materials['Material.205']} />
        <mesh geometry={nodes.Cube034_2.geometry} material={materials['Material.206']} />
      </group>
      <group position={[-57.44, 5.82, -18.29]} rotation={[Math.PI, 0, Math.PI]} scale={[0.03, 0.03, 0.01]}>
        <mesh geometry={nodes.Cube035_1.geometry} material={materials['Material.207']} />
        <mesh geometry={nodes.Cube035_2.geometry} material={materials['Material.208']} />
      </group>
      <group position={[-52.09, 5.82, -18.29]} rotation={[Math.PI, 0, Math.PI]} scale={[0.03, 0.03, 0.01]}>
        <mesh geometry={nodes.Cube036_1.geometry} material={materials['Material.209']} />
        <mesh geometry={nodes.Cube036_2.geometry} material={materials['Material.210']} />
      </group>
      <group position={[-46.86, 5.82, -18.29]} rotation={[Math.PI, 0, Math.PI]} scale={[0.03, 0.03, 0.01]}>
        <mesh geometry={nodes.Cube037_1.geometry} material={materials['Material.211']} />
        <mesh geometry={nodes.Cube037_2.geometry} material={materials['Material.212']} />
      </group>
      <group position={[-41.78, 5.82, -18.29]} rotation={[Math.PI, 0, Math.PI]} scale={[0.03, 0.03, 0.01]}>
        <mesh geometry={nodes.Cube038_1.geometry} material={materials['Material.213']} />
        <mesh geometry={nodes.Cube038_2.geometry} material={materials['Material.214']} />
      </group>
      <group position={[-37.18, 5.82, -18.29]} rotation={[Math.PI, 0, Math.PI]} scale={[0.03, 0.03, 0.01]}>
        <mesh geometry={nodes.Cube039_1.geometry} material={materials['Material.215']} />
        <mesh geometry={nodes.Cube039_2.geometry} material={materials['Material.216']} />
      </group>
      <group position={[-32.52, 5.82, -18.29]} rotation={[Math.PI, 0, Math.PI]} scale={[0.03, 0.03, 0.01]}>
        <mesh geometry={nodes.Cube040_1.geometry} material={materials['Material.217']} />
        <mesh geometry={nodes.Cube040_2.geometry} material={materials['Material.218']} />
      </group>
      <group position={[-39.23, 5.74, -50.13]} rotation={[Math.PI, 0, Math.PI]} scale={[0.03, 0.03, 0.01]}>
        <mesh geometry={nodes.Cube041_1.geometry} material={materials['Material.219']} />
        <mesh geometry={nodes.Cube041_2.geometry} material={materials['Material.220']} />
      </group>
      <group position={[-42.98, 5.74, -50.13]} rotation={[Math.PI, 0, Math.PI]} scale={[0.03, 0.03, 0.01]}>
        <mesh geometry={nodes.Cube042.geometry} material={materials['Material.221']} />
        <mesh geometry={nodes.Cube042_1.geometry} material={materials['Material.222']} />
      </group>
      <group position={[-46.32, 5.74, -50.13]} rotation={[Math.PI, 0, Math.PI]} scale={[0.03, 0.03, 0.01]}>
        <mesh geometry={nodes.Cube043.geometry} material={materials['Material.223']} />
        <mesh geometry={nodes.Cube043_1.geometry} material={materials['Material.224']} />
      </group>
      <group position={[-49.7, 5.74, -50.13]} rotation={[Math.PI, 0, Math.PI]} scale={[0.03, 0.03, 0.01]}>
        <mesh geometry={nodes.Cube044.geometry} material={materials['Material.225']} />
        <mesh geometry={nodes.Cube044_1.geometry} material={materials['Material.226']} />
      </group>
      <group position={[-53.06, 5.74, -50.13]} rotation={[Math.PI, 0, Math.PI]} scale={[0.03, 0.03, 0.01]}>
        <mesh geometry={nodes.Cube045.geometry} material={materials['Material.227']} />
        <mesh geometry={nodes.Cube045_1.geometry} material={materials['Material.228']} />
      </group>
      <group position={[-56.41, 5.74, -50.13]} rotation={[Math.PI, 0, Math.PI]} scale={[0.03, 0.03, 0.01]}>
        <mesh geometry={nodes.Cube046.geometry} material={materials['Material.229']} />
        <mesh geometry={nodes.Cube046_1.geometry} material={materials['Material.230']} />
      </group>
    </group>
  )
}

useGLTF.preload('/3d-model/lsw.gltf')
